name: .NET Core

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
    - name: Publish MenuFramework
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: MenuFramework/MenuFramework.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
